/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ErrorResponse,
  RoleMenuGrant,
  SetSysRoleMenusRequest,
  TenantRoleMenusClearSysRoleMenusParams,
  TenantRoleMenusListSysRoleMenusParams,
  TenantRoleMenusSetSysRoleMenusParams
} from '.././model';





export const tenantRoleMenusListSysRoleMenus = (
    tenantId: string,
    roleId: string,
    params?: TenantRoleMenusListSysRoleMenusParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RoleMenuGrant>> => {
    
    
    return axios.get(
      `/api/v1/tenants/${tenantId}/roles/${roleId}/menus`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getTenantRoleMenusListSysRoleMenusQueryKey = (tenantId?: string,
    roleId?: string,
    params?: TenantRoleMenusListSysRoleMenusParams,) => {
    return [
    `/api/v1/tenants/${tenantId}/roles/${roleId}/menus`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getTenantRoleMenusListSysRoleMenusQueryOptions = <TData = Awaited<ReturnType<typeof tenantRoleMenusListSysRoleMenus>>, TError = AxiosError<ErrorResponse>>(tenantId: string,
    roleId: string,
    params?: TenantRoleMenusListSysRoleMenusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tenantRoleMenusListSysRoleMenus>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTenantRoleMenusListSysRoleMenusQueryKey(tenantId,roleId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof tenantRoleMenusListSysRoleMenus>>> = ({ signal }) => tenantRoleMenusListSysRoleMenus(tenantId,roleId,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(tenantId && roleId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof tenantRoleMenusListSysRoleMenus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TenantRoleMenusListSysRoleMenusQueryResult = NonNullable<Awaited<ReturnType<typeof tenantRoleMenusListSysRoleMenus>>>
export type TenantRoleMenusListSysRoleMenusQueryError = AxiosError<ErrorResponse>


export function useTenantRoleMenusListSysRoleMenus<TData = Awaited<ReturnType<typeof tenantRoleMenusListSysRoleMenus>>, TError = AxiosError<ErrorResponse>>(
 tenantId: string,
    roleId: string,
    params: undefined |  TenantRoleMenusListSysRoleMenusParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof tenantRoleMenusListSysRoleMenus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tenantRoleMenusListSysRoleMenus>>,
          TError,
          Awaited<ReturnType<typeof tenantRoleMenusListSysRoleMenus>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTenantRoleMenusListSysRoleMenus<TData = Awaited<ReturnType<typeof tenantRoleMenusListSysRoleMenus>>, TError = AxiosError<ErrorResponse>>(
 tenantId: string,
    roleId: string,
    params?: TenantRoleMenusListSysRoleMenusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tenantRoleMenusListSysRoleMenus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tenantRoleMenusListSysRoleMenus>>,
          TError,
          Awaited<ReturnType<typeof tenantRoleMenusListSysRoleMenus>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTenantRoleMenusListSysRoleMenus<TData = Awaited<ReturnType<typeof tenantRoleMenusListSysRoleMenus>>, TError = AxiosError<ErrorResponse>>(
 tenantId: string,
    roleId: string,
    params?: TenantRoleMenusListSysRoleMenusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tenantRoleMenusListSysRoleMenus>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTenantRoleMenusListSysRoleMenus<TData = Awaited<ReturnType<typeof tenantRoleMenusListSysRoleMenus>>, TError = AxiosError<ErrorResponse>>(
 tenantId: string,
    roleId: string,
    params?: TenantRoleMenusListSysRoleMenusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tenantRoleMenusListSysRoleMenus>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTenantRoleMenusListSysRoleMenusQueryOptions(tenantId,roleId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const tenantRoleMenusSetSysRoleMenus = (
    tenantId: string,
    roleId: string,
    setSysRoleMenusRequest: SetSysRoleMenusRequest,
    params?: TenantRoleMenusSetSysRoleMenusParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RoleMenuGrant>> => {
    
    
    return axios.put(
      `/api/v1/tenants/${tenantId}/roles/${roleId}/menus`,
      setSysRoleMenusRequest,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getTenantRoleMenusSetSysRoleMenusMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tenantRoleMenusSetSysRoleMenus>>, TError,{tenantId: string;roleId: string;data: SetSysRoleMenusRequest;params?: TenantRoleMenusSetSysRoleMenusParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof tenantRoleMenusSetSysRoleMenus>>, TError,{tenantId: string;roleId: string;data: SetSysRoleMenusRequest;params?: TenantRoleMenusSetSysRoleMenusParams}, TContext> => {

const mutationKey = ['tenantRoleMenusSetSysRoleMenus'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tenantRoleMenusSetSysRoleMenus>>, {tenantId: string;roleId: string;data: SetSysRoleMenusRequest;params?: TenantRoleMenusSetSysRoleMenusParams}> = (props) => {
          const {tenantId,roleId,data,params} = props ?? {};

          return  tenantRoleMenusSetSysRoleMenus(tenantId,roleId,data,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TenantRoleMenusSetSysRoleMenusMutationResult = NonNullable<Awaited<ReturnType<typeof tenantRoleMenusSetSysRoleMenus>>>
    export type TenantRoleMenusSetSysRoleMenusMutationBody = SetSysRoleMenusRequest
    export type TenantRoleMenusSetSysRoleMenusMutationError = AxiosError<ErrorResponse>

    export const useTenantRoleMenusSetSysRoleMenus = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tenantRoleMenusSetSysRoleMenus>>, TError,{tenantId: string;roleId: string;data: SetSysRoleMenusRequest;params?: TenantRoleMenusSetSysRoleMenusParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tenantRoleMenusSetSysRoleMenus>>,
        TError,
        {tenantId: string;roleId: string;data: SetSysRoleMenusRequest;params?: TenantRoleMenusSetSysRoleMenusParams},
        TContext
      > => {

      const mutationOptions = getTenantRoleMenusSetSysRoleMenusMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const tenantRoleMenusClearSysRoleMenus = (
    tenantId: string,
    roleId: string,
    params?: TenantRoleMenusClearSysRoleMenusParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/api/v1/tenants/${tenantId}/roles/${roleId}/menus`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getTenantRoleMenusClearSysRoleMenusMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tenantRoleMenusClearSysRoleMenus>>, TError,{tenantId: string;roleId: string;params?: TenantRoleMenusClearSysRoleMenusParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof tenantRoleMenusClearSysRoleMenus>>, TError,{tenantId: string;roleId: string;params?: TenantRoleMenusClearSysRoleMenusParams}, TContext> => {

const mutationKey = ['tenantRoleMenusClearSysRoleMenus'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tenantRoleMenusClearSysRoleMenus>>, {tenantId: string;roleId: string;params?: TenantRoleMenusClearSysRoleMenusParams}> = (props) => {
          const {tenantId,roleId,params} = props ?? {};

          return  tenantRoleMenusClearSysRoleMenus(tenantId,roleId,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TenantRoleMenusClearSysRoleMenusMutationResult = NonNullable<Awaited<ReturnType<typeof tenantRoleMenusClearSysRoleMenus>>>
    
    export type TenantRoleMenusClearSysRoleMenusMutationError = AxiosError<ErrorResponse>

    export const useTenantRoleMenusClearSysRoleMenus = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tenantRoleMenusClearSysRoleMenus>>, TError,{tenantId: string;roleId: string;params?: TenantRoleMenusClearSysRoleMenusParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tenantRoleMenusClearSysRoleMenus>>,
        TError,
        {tenantId: string;roleId: string;params?: TenantRoleMenusClearSysRoleMenusParams},
        TContext
      > => {

      const mutationOptions = getTenantRoleMenusClearSysRoleMenusMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    