/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { Tenant } from "./tenant";

export type AdminTenantsListTenants200 = {
  items: Tenant[];
  page: number;
  pageSize: number;
  total: number;
};
