/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { OAuthClient } from './oAuthClient';

export type AdminClientsListClients200 = {
  items: OAuthClient[];
  page: number;
  pageSize: number;
  total: number;
};
