/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { AuthorizeCodeRequestResponseType } from './authorizeCodeRequestResponseType';

export interface AuthorizeCodeRequest {
  clientId: string;
  /**
   * @minLength 1
   * @maxLength 500
   */
  redirectUri: string;
  responseType: AuthorizeCodeRequestResponseType;
  scope?: string;
  state: string;
}
