/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type AuthorizeCodeRequestResponseType =
  (typeof AuthorizeCodeRequestResponseType)[keyof typeof AuthorizeCodeRequestResponseType];

export const AuthorizeCodeRequestResponseType = {
  code: "code",
} as const;
