/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export interface CreateSysUserRequest {
  /**
   * @minLength 1
   * @maxLength 64
   */
  username: string;
  /**
   * @minLength 8
   * @maxLength 256
   */
  password: string;
  email?: string;
  mobile?: string;
}
