/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { TenantMembership } from './tenantMembership';

export interface CurrentUser {
  id: string;
  email?: string;
  memberships: TenantMembership[];
  currentTenantId?: string;
}
