/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export interface LoginRequest {
  /**
   * @minLength 1
   * @maxLength 64
   */
  username: string;
  /**
   * @minLength 1
   * @maxLength 128
   */
  password: string;
  clientId: string;
}
