/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { SysUser } from './sysUser';
import type { TenantMembership } from './tenantMembership';

export interface LoginResponse {
  user: SysUser;
  availableTenants: TenantMembership[];
  userId: string;
  currentTenantId?: string;
  accessToken?: string;
  refreshToken?: string;
  tokenType?: string;
  expiresIn?: number;
  clientId: string;
}
