/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { EffectiveMenuNode } from './effectiveMenuNode';

export type MeGetMyMenus200 = {[key: string]: EffectiveMenuNode[]};
