/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export interface RoleMenuGrant {
  roleId: string;
  tenantId: string;
  menuIds: string[];
  updatedAt: string;
}
