/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { LockedAccountResponse } from "./lockedAccountResponse";
import type { ErrorResponse } from "./errorResponse";

export type SessionsLoginDefault = LockedAccountResponse | ErrorResponse;
