/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type SysMenuType = typeof SysMenuType[keyof typeof SysMenuType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SysMenuType = {
  directory: 'directory',
  menu: 'menu',
  button: 'button',
} as const;
