/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type SysMenuType = (typeof SysMenuType)[keyof typeof SysMenuType];

 
export const SysMenuType = {
  directory: "directory",
  menu: "menu",
  button: "button",
} as const;
