/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { SysUserStatus } from './sysUserStatus';

export interface SysUser {
  id: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  username: string;
  email?: string;
  mobile?: string;
  status: SysUserStatus;
  failedAttempts?: number;
  lockedUntil?: string;
  createdAt: string;
  updatedAt: string;
}
