/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type SysUserStatus = typeof SysUserStatus[keyof typeof SysUserStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SysUserStatus = {
  active: 'active',
  invited: 'invited',
  disabled: 'disabled',
} as const;
