/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { TenantMemberUserView } from './tenantMemberUserView';

export type TenantMembersListTenantUsers200 = {
  items: TenantMemberUserView[];
  page: number;
  pageSize: number;
  total: number;
};
