/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type TenantStatus = (typeof TenantStatus)[keyof typeof TenantStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TenantStatus = {
  active: "active",
  suspended: "suspended",
} as const;
