/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { TenantApplication } from './tenantApplication';

export type TenantApplicationsListTenantApplications200 = {
  items: TenantApplication[];
  page: number;
  pageSize: number;
  total: number;
};
