/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { SysRole } from './sysRole';

export type TenantRolesListSysRoles200 = {
  items: SysRole[];
  page: number;
  pageSize: number;
  total: number;
};
