/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { TenantMemberStatus } from './tenantMemberStatus';

export interface TenantMember {
  id: string;
  tenantId: string;
  userId: string;
  memberName?: string;
  isOwner: boolean;
  status: TenantMemberStatus;
  createdAt: string;
  updatedAt: string;
}
