/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type TenantMemberStatus = (typeof TenantMemberStatus)[keyof typeof TenantMemberStatus];

 
export const TenantMemberStatus = {
  active: "active",
  invited: "invited",
  suspended: "suspended",
  disabled: "disabled",
} as const;
