/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { TenantMemberStatus } from "./tenantMemberStatus";

export interface TenantMemberUserView {
  id: string;
  tenantId: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  username: string;
  email?: string;
  status: TenantMemberStatus;
  roleIds: string[];
  createdAt: string;
  updatedAt: string;
}
