/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type TenantMemberStatus = typeof TenantMemberStatus[keyof typeof TenantMemberStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TenantMemberStatus = {
  active: 'active',
  disabled: 'disabled',
} as const;
