/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { TenantStatus } from './tenantStatus';

export interface Tenant {
  id: string;
  /**
   * @minLength 2
   * @maxLength 64
   */
  tenantKey: string;
  /**
   * @minLength 2
   * @maxLength 128
   */
  name: string;
  status: TenantStatus;
  createdAt: string;
  updatedAt: string;
}
