/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { TenantMember } from './tenantMember';
import type { SysUser } from './sysUser';

export interface TenantMemberView {
  member: TenantMember;
  user: SysUser;
  roles: string[];
}
