/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export interface TenantApplication {
  id: string;
  tenantId: string;
  clientId: string;
  status: number;
  expireTime?: string;
  createdAt: string;
}
