/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { TokenRequestGrantType } from "./tokenRequestGrantType";

export interface TokenRequest {
  grantType: TokenRequestGrantType;
  code?: string;
  refreshToken?: string;
  clientId: string;
  clientSecret?: string;
  redirectUri?: string;
}
