/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { TenantStatus } from './tenantStatus';

export interface UpdateTenantRequest {
  /**
   * @minLength 2
   * @maxLength 128
   */
  name?: string;
  status?: TenantStatus;
}
