/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export interface UpdateSysRoleRequest {
  /**
   * @minLength 1
   * @maxLength 64
   */
  roleName?: string;
  description?: string;
  status?: number;
}
