/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export interface UpdateOAuthClientRequest {
  clientName?: string;
  grantTypes?: string;
  redirectUris?: string;
  scopes?: string;
  accessTokenValidity?: number;
  refreshTokenValidity?: number;
  autoApprove?: boolean;
  status?: number;
}
