/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { SysUserStatus } from './sysUserStatus';

export interface UpdateSysUserRequest {
  email?: string;
  mobile?: string;
  status?: SysUserStatus;
}
