/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  LoginRequest,
  LoginResponse,
  SessionsLoginDefault
} from '.././model';





export const sessionsLogin = (
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LoginResponse>> => {
    
    
    return axios.post(
      `/api/v1/auth/login`,
      loginRequest,options
    );
  }



export const getSessionsLoginMutationOptions = <TError = AxiosError<SessionsLoginDefault>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sessionsLogin>>, TError,{data: LoginRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof sessionsLogin>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['sessionsLogin'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sessionsLogin>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  sessionsLogin(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SessionsLoginMutationResult = NonNullable<Awaited<ReturnType<typeof sessionsLogin>>>
    export type SessionsLoginMutationBody = LoginRequest
    export type SessionsLoginMutationError = AxiosError<SessionsLoginDefault>

    export const useSessionsLogin = <TError = AxiosError<SessionsLoginDefault>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sessionsLogin>>, TError,{data: LoginRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sessionsLogin>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {

      const mutationOptions = getSessionsLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const sessionsLogout = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.post(
      `/api/v1/auth/logout`,undefined,options
    );
  }



export const getSessionsLogoutMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sessionsLogout>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof sessionsLogout>>, TError,void, TContext> => {

const mutationKey = ['sessionsLogout'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sessionsLogout>>, void> = () => {
          

          return  sessionsLogout(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SessionsLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof sessionsLogout>>>
    
    export type SessionsLogoutMutationError = AxiosError<unknown>

    export const useSessionsLogout = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sessionsLogout>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sessionsLogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getSessionsLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    