/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  CreateSysUserRequest,
  ErrorResponse,
  SetTenantMemberRolesRequest,
  TenantMemberUserView,
  TenantMemberView,
  TenantMembersChangeTenantUserStatusBody,
  TenantMembersInviteTenantUserBody,
  TenantMembersListTenantUsers200,
  TenantMembersListTenantUsersParams,
  UpdateSysUserRequest,
} from ".././model";

export const tenantMembersListTenantUsers = (
  tenantId: string,
  params?: TenantMembersListTenantUsersParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TenantMembersListTenantUsers200>> => {
  return axios.get(`/api/v1/tenants/${tenantId}/members`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getTenantMembersListTenantUsersQueryKey = (
  tenantId?: string,
  params?: TenantMembersListTenantUsersParams,
) => {
  return [`/api/v1/tenants/${tenantId}/members`, ...(params ? [params] : [])] as const;
};

export const getTenantMembersListTenantUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof tenantMembersListTenantUsers>>,
  TError = AxiosError<ErrorResponse>,
>(
  tenantId: string,
  params?: TenantMembersListTenantUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tenantMembersListTenantUsers>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getTenantMembersListTenantUsersQueryKey(tenantId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof tenantMembersListTenantUsers>>> = ({
    signal,
  }) => tenantMembersListTenantUsers(tenantId, params, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!tenantId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof tenantMembersListTenantUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TenantMembersListTenantUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof tenantMembersListTenantUsers>>
>;
export type TenantMembersListTenantUsersQueryError = AxiosError<ErrorResponse>;

export function useTenantMembersListTenantUsers<
  TData = Awaited<ReturnType<typeof tenantMembersListTenantUsers>>,
  TError = AxiosError<ErrorResponse>,
>(
  tenantId: string,
  params: undefined | TenantMembersListTenantUsersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tenantMembersListTenantUsers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tenantMembersListTenantUsers>>,
          TError,
          Awaited<ReturnType<typeof tenantMembersListTenantUsers>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTenantMembersListTenantUsers<
  TData = Awaited<ReturnType<typeof tenantMembersListTenantUsers>>,
  TError = AxiosError<ErrorResponse>,
>(
  tenantId: string,
  params?: TenantMembersListTenantUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tenantMembersListTenantUsers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tenantMembersListTenantUsers>>,
          TError,
          Awaited<ReturnType<typeof tenantMembersListTenantUsers>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTenantMembersListTenantUsers<
  TData = Awaited<ReturnType<typeof tenantMembersListTenantUsers>>,
  TError = AxiosError<ErrorResponse>,
>(
  tenantId: string,
  params?: TenantMembersListTenantUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tenantMembersListTenantUsers>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useTenantMembersListTenantUsers<
  TData = Awaited<ReturnType<typeof tenantMembersListTenantUsers>>,
  TError = AxiosError<ErrorResponse>,
>(
  tenantId: string,
  params?: TenantMembersListTenantUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tenantMembersListTenantUsers>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTenantMembersListTenantUsersQueryOptions(tenantId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const tenantMembersCreateTenantUser = (
  tenantId: string,
  createSysUserRequest: CreateSysUserRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TenantMemberUserView>> => {
  return axios.post(`/api/v1/tenants/${tenantId}/members`, createSysUserRequest, options);
};

export const getTenantMembersCreateTenantUserMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tenantMembersCreateTenantUser>>,
    TError,
    { tenantId: string; data: CreateSysUserRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tenantMembersCreateTenantUser>>,
  TError,
  { tenantId: string; data: CreateSysUserRequest },
  TContext
> => {
  const mutationKey = ["tenantMembersCreateTenantUser"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tenantMembersCreateTenantUser>>,
    { tenantId: string; data: CreateSysUserRequest }
  > = (props) => {
    const { tenantId, data } = props ?? {};

    return tenantMembersCreateTenantUser(tenantId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TenantMembersCreateTenantUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof tenantMembersCreateTenantUser>>
>;
export type TenantMembersCreateTenantUserMutationBody = CreateSysUserRequest;
export type TenantMembersCreateTenantUserMutationError = AxiosError<ErrorResponse>;

export const useTenantMembersCreateTenantUser = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tenantMembersCreateTenantUser>>,
      TError,
      { tenantId: string; data: CreateSysUserRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof tenantMembersCreateTenantUser>>,
  TError,
  { tenantId: string; data: CreateSysUserRequest },
  TContext
> => {
  const mutationOptions = getTenantMembersCreateTenantUserMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const tenantMembersInviteTenantUser = (
  tenantId: string,
  tenantMembersInviteTenantUserBody: TenantMembersInviteTenantUserBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TenantMemberView>> => {
  return axios.post(
    `/api/v1/tenants/${tenantId}/members/invitations`,
    tenantMembersInviteTenantUserBody,
    options,
  );
};

export const getTenantMembersInviteTenantUserMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tenantMembersInviteTenantUser>>,
    TError,
    { tenantId: string; data: TenantMembersInviteTenantUserBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tenantMembersInviteTenantUser>>,
  TError,
  { tenantId: string; data: TenantMembersInviteTenantUserBody },
  TContext
> => {
  const mutationKey = ["tenantMembersInviteTenantUser"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tenantMembersInviteTenantUser>>,
    { tenantId: string; data: TenantMembersInviteTenantUserBody }
  > = (props) => {
    const { tenantId, data } = props ?? {};

    return tenantMembersInviteTenantUser(tenantId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TenantMembersInviteTenantUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof tenantMembersInviteTenantUser>>
>;
export type TenantMembersInviteTenantUserMutationBody = TenantMembersInviteTenantUserBody;
export type TenantMembersInviteTenantUserMutationError = AxiosError<ErrorResponse>;

export const useTenantMembersInviteTenantUser = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tenantMembersInviteTenantUser>>,
      TError,
      { tenantId: string; data: TenantMembersInviteTenantUserBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof tenantMembersInviteTenantUser>>,
  TError,
  { tenantId: string; data: TenantMembersInviteTenantUserBody },
  TContext
> => {
  const mutationOptions = getTenantMembersInviteTenantUserMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const tenantMembersGetTenantUser = (
  tenantId: string,
  userId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TenantMemberUserView>> => {
  return axios.get(`/api/v1/tenants/${tenantId}/members/${userId}`, options);
};

export const getTenantMembersGetTenantUserQueryKey = (tenantId?: string, userId?: string) => {
  return [`/api/v1/tenants/${tenantId}/members/${userId}`] as const;
};

export const getTenantMembersGetTenantUserQueryOptions = <
  TData = Awaited<ReturnType<typeof tenantMembersGetTenantUser>>,
  TError = AxiosError<ErrorResponse>,
>(
  tenantId: string,
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tenantMembersGetTenantUser>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getTenantMembersGetTenantUserQueryKey(tenantId, userId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof tenantMembersGetTenantUser>>> = ({
    signal,
  }) => tenantMembersGetTenantUser(tenantId, userId, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!(tenantId && userId), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof tenantMembersGetTenantUser>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TenantMembersGetTenantUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof tenantMembersGetTenantUser>>
>;
export type TenantMembersGetTenantUserQueryError = AxiosError<ErrorResponse>;

export function useTenantMembersGetTenantUser<
  TData = Awaited<ReturnType<typeof tenantMembersGetTenantUser>>,
  TError = AxiosError<ErrorResponse>,
>(
  tenantId: string,
  userId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tenantMembersGetTenantUser>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tenantMembersGetTenantUser>>,
          TError,
          Awaited<ReturnType<typeof tenantMembersGetTenantUser>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTenantMembersGetTenantUser<
  TData = Awaited<ReturnType<typeof tenantMembersGetTenantUser>>,
  TError = AxiosError<ErrorResponse>,
>(
  tenantId: string,
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tenantMembersGetTenantUser>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tenantMembersGetTenantUser>>,
          TError,
          Awaited<ReturnType<typeof tenantMembersGetTenantUser>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTenantMembersGetTenantUser<
  TData = Awaited<ReturnType<typeof tenantMembersGetTenantUser>>,
  TError = AxiosError<ErrorResponse>,
>(
  tenantId: string,
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tenantMembersGetTenantUser>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useTenantMembersGetTenantUser<
  TData = Awaited<ReturnType<typeof tenantMembersGetTenantUser>>,
  TError = AxiosError<ErrorResponse>,
>(
  tenantId: string,
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tenantMembersGetTenantUser>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTenantMembersGetTenantUserQueryOptions(tenantId, userId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const tenantMembersUpdateTenantUser = (
  tenantId: string,
  userId: string,
  updateSysUserRequest: UpdateSysUserRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TenantMemberUserView>> => {
  return axios.patch(
    `/api/v1/tenants/${tenantId}/members/${userId}`,
    updateSysUserRequest,
    options,
  );
};

export const getTenantMembersUpdateTenantUserMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tenantMembersUpdateTenantUser>>,
    TError,
    { tenantId: string; userId: string; data: UpdateSysUserRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tenantMembersUpdateTenantUser>>,
  TError,
  { tenantId: string; userId: string; data: UpdateSysUserRequest },
  TContext
> => {
  const mutationKey = ["tenantMembersUpdateTenantUser"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tenantMembersUpdateTenantUser>>,
    { tenantId: string; userId: string; data: UpdateSysUserRequest }
  > = (props) => {
    const { tenantId, userId, data } = props ?? {};

    return tenantMembersUpdateTenantUser(tenantId, userId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TenantMembersUpdateTenantUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof tenantMembersUpdateTenantUser>>
>;
export type TenantMembersUpdateTenantUserMutationBody = UpdateSysUserRequest;
export type TenantMembersUpdateTenantUserMutationError = AxiosError<ErrorResponse>;

export const useTenantMembersUpdateTenantUser = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tenantMembersUpdateTenantUser>>,
      TError,
      { tenantId: string; userId: string; data: UpdateSysUserRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof tenantMembersUpdateTenantUser>>,
  TError,
  { tenantId: string; userId: string; data: UpdateSysUserRequest },
  TContext
> => {
  const mutationOptions = getTenantMembersUpdateTenantUserMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const tenantMembersDeleteTenantUser = (
  tenantId: string,
  userId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.delete(`/api/v1/tenants/${tenantId}/members/${userId}`, options);
};

export const getTenantMembersDeleteTenantUserMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tenantMembersDeleteTenantUser>>,
    TError,
    { tenantId: string; userId: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tenantMembersDeleteTenantUser>>,
  TError,
  { tenantId: string; userId: string },
  TContext
> => {
  const mutationKey = ["tenantMembersDeleteTenantUser"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tenantMembersDeleteTenantUser>>,
    { tenantId: string; userId: string }
  > = (props) => {
    const { tenantId, userId } = props ?? {};

    return tenantMembersDeleteTenantUser(tenantId, userId, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TenantMembersDeleteTenantUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof tenantMembersDeleteTenantUser>>
>;

export type TenantMembersDeleteTenantUserMutationError = AxiosError<ErrorResponse>;

export const useTenantMembersDeleteTenantUser = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tenantMembersDeleteTenantUser>>,
      TError,
      { tenantId: string; userId: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof tenantMembersDeleteTenantUser>>,
  TError,
  { tenantId: string; userId: string },
  TContext
> => {
  const mutationOptions = getTenantMembersDeleteTenantUserMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const tenantMembersAssignTenantMemberRoles = (
  tenantId: string,
  userId: string,
  setTenantMemberRolesRequest: SetTenantMemberRolesRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TenantMemberUserView>> => {
  return axios.put(
    `/api/v1/tenants/${tenantId}/members/${userId}/roles`,
    setTenantMemberRolesRequest,
    options,
  );
};

export const getTenantMembersAssignTenantMemberRolesMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tenantMembersAssignTenantMemberRoles>>,
    TError,
    { tenantId: string; userId: string; data: SetTenantMemberRolesRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tenantMembersAssignTenantMemberRoles>>,
  TError,
  { tenantId: string; userId: string; data: SetTenantMemberRolesRequest },
  TContext
> => {
  const mutationKey = ["tenantMembersAssignTenantMemberRoles"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tenantMembersAssignTenantMemberRoles>>,
    { tenantId: string; userId: string; data: SetTenantMemberRolesRequest }
  > = (props) => {
    const { tenantId, userId, data } = props ?? {};

    return tenantMembersAssignTenantMemberRoles(tenantId, userId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TenantMembersAssignTenantMemberRolesMutationResult = NonNullable<
  Awaited<ReturnType<typeof tenantMembersAssignTenantMemberRoles>>
>;
export type TenantMembersAssignTenantMemberRolesMutationBody = SetTenantMemberRolesRequest;
export type TenantMembersAssignTenantMemberRolesMutationError = AxiosError<ErrorResponse>;

export const useTenantMembersAssignTenantMemberRoles = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tenantMembersAssignTenantMemberRoles>>,
      TError,
      { tenantId: string; userId: string; data: SetTenantMemberRolesRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof tenantMembersAssignTenantMemberRoles>>,
  TError,
  { tenantId: string; userId: string; data: SetTenantMemberRolesRequest },
  TContext
> => {
  const mutationOptions = getTenantMembersAssignTenantMemberRolesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const tenantMembersChangeTenantUserStatus = (
  tenantId: string,
  userId: string,
  tenantMembersChangeTenantUserStatusBody: TenantMembersChangeTenantUserStatusBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TenantMemberUserView>> => {
  return axios.patch(
    `/api/v1/tenants/${tenantId}/members/${userId}/status`,
    tenantMembersChangeTenantUserStatusBody,
    options,
  );
};

export const getTenantMembersChangeTenantUserStatusMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tenantMembersChangeTenantUserStatus>>,
    TError,
    { tenantId: string; userId: string; data: TenantMembersChangeTenantUserStatusBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tenantMembersChangeTenantUserStatus>>,
  TError,
  { tenantId: string; userId: string; data: TenantMembersChangeTenantUserStatusBody },
  TContext
> => {
  const mutationKey = ["tenantMembersChangeTenantUserStatus"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tenantMembersChangeTenantUserStatus>>,
    { tenantId: string; userId: string; data: TenantMembersChangeTenantUserStatusBody }
  > = (props) => {
    const { tenantId, userId, data } = props ?? {};

    return tenantMembersChangeTenantUserStatus(tenantId, userId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TenantMembersChangeTenantUserStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof tenantMembersChangeTenantUserStatus>>
>;
export type TenantMembersChangeTenantUserStatusMutationBody =
  TenantMembersChangeTenantUserStatusBody;
export type TenantMembersChangeTenantUserStatusMutationError = AxiosError<ErrorResponse>;

export const useTenantMembersChangeTenantUserStatus = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tenantMembersChangeTenantUserStatus>>,
      TError,
      { tenantId: string; userId: string; data: TenantMembersChangeTenantUserStatusBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof tenantMembersChangeTenantUserStatus>>,
  TError,
  { tenantId: string; userId: string; data: TenantMembersChangeTenantUserStatusBody },
  TContext
> => {
  const mutationOptions = getTenantMembersChangeTenantUserStatusMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
